### PR TITLE
Add get Episodes Summary

### PR DESCRIPTION
**Pull request by ClementKerneur**

### CODE REVIEW

**Comment by edwellbrook** [comment]
Hey @ClementKerneur! Thanks so much for the pull request. Look’s like there are some linting errors due to whitespace.

Additionally the PR is missing tests. If you can add some and fix the linting error, I’d love to get this merged in.

For reference, here’s a similar PR with tests: https://github.com/edwellbrook/node-tvdb/pull/81

Cheers!

**Comment by ClementKerneur** [comment]
Ok thanks, the PR #81 are exacly this equivalent.

So, I close this PR.
Thanks you for response.

**Comment by ClementKerneur** [comment]
Thanks @edwellbrook i wasn't understand...

I've write test for this new methods and solve problems of linting.

I think that is now good :)

**Comment by edwellbrook** [comment]
Looks great. Thanks for updating that @ClementKerneur. Merged, updated the docs, and published a new version to npm (`v4.1.0`).

Thanks again for your contribution! 😄

**Pull request merged**
