### PR TITLE
API updates

### PR DESCRIPTION
**Pull request by jhutchins**
Enriched the `getEpisodesBySeriesId` function to allow adding a query so that episodes can be filtered by things like season and episode number.

Added a method for getting season posters.

### CODE REVIEW

**Comment by edwellbrook** [comment]
Hey Jeffrey! Thanks for the pull request, looks great!

Only thing missing is some tests :) Could you
- add a test for `getSeasonPosters` (something similar to [`/test/getSeriesPosters.js`](https://github.com/edwellbrook/node-tvdb/blob/14bb1783b7e289e24686f19c5a2642761f614694/test/getSeriesPosters.js) would be great)
- add a test to [`/test/getEpisodesBySeriesId`](https://github.com/edwellbrook/node-tvdb/blob/295d573c21dac345402648785f346a48c43d2f2a/test/getEpisodesBySeriesId.js) for a request that makes use of the `query` url

Looking forward to getting this merged 😄

**Comment by jhutchins** [comment]
@edwellbrook you're right, I was "light" on the testing. I now humbly submit for your consideration, the same features; now with tests! 😉

**Comment by edwellbrook** [comment]
Thanks for your contribution! Tidying some other bits of the library up, and will update on npm shortly :)

**Comment by edwellbrook** [comment]
Just published `v3.2.0` to npm. Thanks again for contributing! 😄

**Comment by jhutchins** [comment]
Thank you for writing this library in the first place.

**Pull request merged**
