### PR TITLE
Added getEpisodesById to get only episodes from all-api

### PR DESCRIPTION
**Pull request by yusiswtor**
See commit comment :)

### CODE REVIEW

**Comment by edwellbrook** [comment]
Hey! Thanks so much for the pull request. I'd love to add this to the project but before I can merge could you:
- add a link to relevant documentation from thetvdb website for the api endpoint, if you can/it exists
- write and include some tests for this new method in your pull requests

If you have any trouble with either of those, let me know :) Once they've been dealt with, I'll get this merged. Thanks!

**Comment by yusiswtor** [comment]
Will look at that tomorrow, was probably a bit triggerhappy with the pull request!

**Comment by edwellbrook** [comment]
no worries! I'm looking forward to getting this merged in! :smile:

**Comment by yusiswtor** [comment]
Added some tests now, hopefully those are enough! Also linked docs and explained what it does!

**Comment by edwellbrook** [comment]
Thanks for your contribution. Just merged your PR, and added the new method to the README. Updated on npm, for version `1.5.0`. :smile:

**Pull request merged**
