### PR TITLE
getSeries isn't a function, getSeriesByName is.

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by edwellbrook** [comment]
Great spot. Thanks for this! Merged.

**Comment by OmgImAlexis** [comment]
You're welcome, sat here for about an hour trying to workout what was broken. haha

**Comment by edwellbrook** [comment]
oh man, really sorry about that! thanks again :)

**Comment by OmgImAlexis** [comment]
All's good, npmjs.com needs updating too.

**Comment by edwellbrook** [comment]
yep, was looking into if i could update the readme without bumping the version number. sadly not possible so bumped and published. :smile:

**Pull request merged**
